### ISSUE TITLE
Fails to correctly encode "aswf!@#$%^&*()"

### ISSUE THREAD

**Issue by BafDyce** [magiclen/base64-url#1]
```rust
base64_url::encode("aswf!@#$%^&*()")
```

returns `"YXN3ZiFAIyQlXiYqKCk"`

Attempting to decode this with Linux' base64 binary fails:

```bash
$ echo "YXN3ZiFAIyQlXiYqKCk" | base64 -d
aswf!@#$%^&*()base64: invalid input
```

This is the correct base64 encoding (trailing `'='`!):

```bash
$ echo -n 'aswf!@#$%^&*()' | base64
YXN3ZiFAIyQlXiYqKCk=
```

The [base64](https://crates.io/crates/base64)-crate correctly encodes the string, so I don't know where base64_url goes wrong.

**Comment by magiclen** [comment]
Do you know the difference between Base64-standard and Base64-url?

See https://tools.ietf.org/html/rfc4648#section-5

**Comment by BafDyce** [comment]
Oh, sorry. I was not aware that the trailing padding can be optional in base64-url.
